import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Box, ChakraProvider, Flex } from '@chakra-ui/react'
import NavBar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <ChakraProvider>
            <Flex width={"100vw"} minHeight={"100vh"} flexDirection={"column"}>
              <NavBar loggedIn={true}/>
              <Flex flex={1} width={"100%"} minHeight={"100%"}>{children}</Flex>
            </Flex>
          </ChakraProvider>
        </body>
    </html>
  )
}
